name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      Solution_Name: ./ShopingCenter/ShopingCenter.sln
      
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore
      run: dotnet restore 'ShopingCenter/ShopingCenter.sln'
    - name: Build
      run: dotnet build 'ShopingCenter/ShopingCenter.sln' --no-restore

