name: build
on: [push]

jobs:
  job1:
    name: build
    runs-on: ubuntu-latest
    
    steps:  
      - task: Setup .NET 5
        displayName: Install .NET 5
        inputs:
          version: 5.0.x
          
      - task: DotNetCoreCLI@2
        displayName: dotnet restore
        inputs:
          command: restore
          projects: ShopingCenter/ShopingCenter.sln
          nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
          command: build
          projects: ShopingCenter/ShopingCenter.sln
          arguments: --no-restore -c Release -v n
